name: exgood
version: 1
accesskey: 32zkl52y52

cron:
- url: /update
  schedule: "5 0 * * *"

libraries:
- name: webpy
  version: "0.36"

- name: lxml
  version: "2.3.4"

- name: MySQLdb
  version: "1.2.3"
...